################################################################
################################################################
####
#### This makefile is part of the source of 
#### "Parallel Programming in MPI and OpenMP"
#### by Victor Eijkhout, copyright 2013-2020
####
#### Makefile for DDT course slides
####
################################################################
################################################################

info::

COURSE = ddt
COURSES = ddt
FILE = ddt_course
INEX = tacc-full
EXTRATEXINPUTS = :${HOME}/Software/TeX/LaTeX//

include ../course-support/Make.course
DROPBOXPATH = Courses
include ../../booksources/makefiles/Make.clean
