################################################################
################################################################
####
#### This makefile is part of the source of 
#### "Parallel Programming in MPI and OpenMP"
#### by Victor Eijkhout, copyright 2013-8
####
#### Makefile for course support
####
################################################################
################################################################

include Make.clean
