################################################################
################################################################
####
#### This makefile is part of the source of 
#### "Parallel Programming in MPI and OpenMP"
#### by Victor Eijkhout, copyright 2013-2025
####
#### Makefile for course support
####
################################################################
################################################################

include ../../makefiles/Make.clean
