# -*- makefile -*-
################################################################
################################################################
####
#### This make file is part of the source of 
#### `Parallel Programing in Science and Engineering'
#### by Victor Eijkhout, copyright 2013-2022
####
#### Makefile for code snippets
####
################################################################
################################################################

PUBLICALL = 1
include ../makefiles/Make.public

include ../makefiles/Make.clean
