################################################################
####
#### This makefile is part of the tutorial
#### `Introduction to the PETSc library'
#### by Victor Eijkhout eijkhout@tacc.utexas.edu
####
#### copyright Victor Eijkhout 2012-2022
####
#### makefile for PETSc course slides
####
################################################################

info ::

COURSE = petsc
COURSES = petsc
FILE = petsc_course
FILES = petsc_course petsc-handout

EXTRATEXINPUTS=:../../petscreference
LANGUAGE = all
LANGUAGES = f p c
include ../course-support/Make.course

DROPBOXPATH = Courses
include ../../booksources/makefiles/Make.clean
