################################################################
################################################################
####
#### This makefile is part of the source of 
#### "Parallel Programming in MPI and OpenMP"
#### by Victor Eijkhout, copyright 2013-2022
####
#### Makefile for OpenMP course slides
####
################################################################
################################################################

info::

COURSE = omp
COURSES = omp omptopics
FILE = omp_course
INEX = tacc-full

include ../course-support/Make.course
DROPBOXPATH = Courses

include ../../booksources/makefiles/Make.clean
