# -*- makefile -*-
################################################################
################################################################
####
#### This make file is part of the source of 
#### `Parallel Programing in Science and Engineering'
#### by Victor Eijkhout, copyright 2013-2021
####
#### Makefile for the exercises directory
####
################################################################
################################################################

include ../makefiles/Make.clean
MAKEFILESDIR := ../${MAKEFILESDIR}
MAKETRACESTRING := "${MAKETRACESTRING} .."
